spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET_KEY}

mail:
  from:
    address: ${MAIL_NAME}

h2:
  console:
    enabled: true
    path: /h2-console

s3:
  bucket: ${S3_BUCKET_NAME}
  endpoint: ${S3_END_POINT}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  public-url: ${S3_PUBLIC_URL}
